import './style.css';
import {TilingEngine,type Hat,type Point} from './math/tiling';
import {AudioEngine} from './audio';import {loadSave,save,type Save} from './persistence';

const canvas=document.querySelector<HTMLCanvasElement>('#universe')!,ctx=canvas.getContext('2d')!,undoBtn=document.querySelector<HTMLButtonElement>('#undo')!,resetBtn=document.querySelector<HTMLButtonElement>('#reset')!,soundBtn=document.querySelector<HTMLButtonElement>('#sound')!,message=document.querySelector<HTMLDivElement>('#message')!;
const engine=new TilingEngine(3),audio=new AudioEngine();let opened=new Set<string>(),undo:string[]=[],cam={x:0,y:0,zoom:42},cover=new Image(),space=new Image(),drag:undefined|{x:number;y:number;angle:number;mirrored:boolean},mode:'move'|'rotate'='move',active=false,isTouch=false,pointerStart:Point={x:0,y:0},pointer:Point={x:0,y:0},panning=false,last=pointer,hintElapsed=0,hintTick=0,hint:Hat|undefined,snap:Hat|undefined,opening=new Map<string,number>(),dirtySave=0;
cover.src=`${import.meta.env.BASE_URL}assets/cover/opening.png?v=20260823-2`;space.src=`${import.meta.env.BASE_URL}assets/universe/ultra_deep_field.png`;
const world=(q:Point)=>({x:(q.x-canvas.clientWidth/2)/cam.zoom+cam.x,y:(q.y-canvas.clientHeight/2)/cam.zoom+cam.y}),screen=(q:Point)=>({x:(q.x-cam.x)*cam.zoom+canvas.clientWidth/2,y:(q.y-cam.y)*cam.zoom+canvas.clientHeight/2});
const path=(poly:Point[])=>{const q=new Path2D();poly.forEach((v,i)=>i?q.lineTo(v.x,v.y):q.moveTo(v.x,v.y));q.closePath();return q};
const d2=(a:Point,b:Point)=>(a.x-b.x)**2+(a.y-b.y)**2;
const normAngle=(a:number)=>Math.atan2(Math.sin(a),Math.cos(a));
const desiredAngle=(h:Hat)=>{const base=engine.hats.get(engine.initialId())!;return normAngle(Math.atan2(h.T[3],h.T[0])-Math.atan2(base.T[3],base.T[0]))};
function dragPolygon(){if(!drag)return[];const base=engine.hats.get(engine.initialId())!,c=Math.cos(drag.angle),s=Math.sin(drag.angle),flip=drag.mirrored?-1:1;return base.polygon.map(v=>{const x=(v.x-base.center.x)*flip,y=v.y-base.center.y;return{x:drag!.x+c*x-s*y,y:drag!.y+s*x+c*y}})}
function inside(q:Point,poly:Point[]){let hit=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const a=poly[i],b=poly[j];if((a.y>q.y)!==(b.y>q.y)&&q.x<(b.x-a.x)*(q.y-a.y)/(b.y-a.y)+a.x)hit=!hit}return hit}
function partHit(q:Point):'move'|'rotate'|'outside'{const poly=dragPolygon(),radius=(isTouch?30:18)/cam.zoom;if(poly.some(v=>d2(v,q)<=radius*radius))return'rotate';return inside(q,poly)?'move':'outside'}
function nearestFrontier(){let best:Hat|undefined,score=Infinity;if(!drag)return;for(const id of engine.frontier(opened)){const h=engine.hats.get(id)!,da=Math.abs(normAngle(desiredAngle(h)-drag.angle)),s=d2(h.center,drag)+da*da*2+(h.mirrored===drag.mirrored?0:.3);if(s<score){score=s;best=h}}return best}
function persist(){clearTimeout(dirtySave);dirtySave=window.setTimeout(()=>save({schemaVersion:1,mathRuleSetVersion:'hat-htpf-v1',openedHatIds:[...opened],undo,camera:cam,audio:{muted:audio.muted,volume:audio.volume}}),180)}
function spawnHat(playSound=false){const base=engine.hats.get(engine.initialId())!,q=world({x:Math.max(120,canvas.clientWidth*.78),y:Math.max(160,canvas.clientHeight*.72)});drag={x:q.x,y:q.y,angle:0,mirrored:base.mirrored};canvas.dataset.part='ready';mode='move';active=false;hintElapsed=0;hint=undefined;snap=undefined;if(playSound)audio.appears()}
function reset(){const id=engine.initialId();opened=new Set([id]);undo=[];cam={x:engine.hats.get(id)!.center.x,y:engine.hats.get(id)!.center.y,zoom:42};hint=undefined;spawnHat();persist()}
function resize(){const d=devicePixelRatio||1,rect=canvas.getBoundingClientRect();canvas.width=Math.round(rect.width*d);canvas.height=Math.round(rect.height*d);ctx.setTransform(d,0,0,d,0,0);draw()}
function drawImageWorld(img:HTMLImageElement,alpha=1){if(!img.complete||!img.naturalWidth)return;ctx.save();ctx.globalAlpha=alpha;const scale=Math.max(canvas.clientWidth/img.naturalWidth,canvas.clientHeight/img.naturalHeight)*1.2,w=img.naturalWidth*scale,h=img.naturalHeight*scale;ctx.drawImage(img,-cam.x*cam.zoom+canvas.clientWidth/2-w/2,-cam.y*cam.zoom+canvas.clientHeight/2-h/2,w,h);ctx.restore()}
function draw(){const d=devicePixelRatio||1,W=canvas.width/d,H=canvas.height/d;canvas.dataset.renderPart=drag?`${Math.round((drag.x-cam.x)*cam.zoom+W/2)},${Math.round((drag.y-cam.y)*cam.zoom+H/2)}`:'none';ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,W,H);ctx.fillStyle='#11141b';ctx.fillRect(0,0,W,H);drawImageWorld(cover,.94);const now=performance.now();if(active&&drag&&!panning){if(hintTick)hintElapsed+=now-hintTick;hintTick=now;if(!hint&&hintElapsed>=7000)hint=nearestFrontier()}else hintTick=0;ctx.save();ctx.beginPath();ctx.save();ctx.translate(W/2-cam.x*cam.zoom,H/2-cam.y*cam.zoom);ctx.scale(cam.zoom,cam.zoom);for(const id of opened){const h=engine.hats.get(id);if(!h)continue;const t=opening.get(id),k=t?Math.min(1,(now-t)/420):1;ctx.save();ctx.translate(h.center.x,h.center.y);ctx.scale(k,k);ctx.translate(-h.center.x,-h.center.y);const hp=h.polygon;hp.forEach((v,i)=>i?ctx.lineTo(v.x,v.y):ctx.moveTo(v.x,v.y));ctx.closePath();ctx.restore();if(k>=1)opening.delete(id)}ctx.restore();ctx.clip();drawImageWorld(space);ctx.restore();
 ctx.save();ctx.translate(W/2-cam.x*cam.zoom,H/2-cam.y*cam.zoom);ctx.scale(cam.zoom,cam.zoom);ctx.lineWidth=1/cam.zoom;ctx.strokeStyle='#d9e8ff55';for(const id of opened){const h=engine.hats.get(id);if(h)ctx.stroke(path(h.polygon))}if(hint){ctx.save();ctx.setLineDash([.14,.12]);ctx.lineWidth=3/cam.zoom;ctx.strokeStyle=drag?.mirrored===hint.mirrored?'#c6e8ff':'#ffd48a';ctx.fillStyle='#b8dfff1b';ctx.fill(path(hint.polygon));ctx.stroke(path(hint.polygon));ctx.restore()}if(snap){ctx.lineWidth=4/cam.zoom;ctx.strokeStyle='#e9fbff';ctx.stroke(path(snap.polygon))}if(drag){const base=engine.hats.get(engine.initialId())!,local=base.polygon.map(v=>({x:v.x-base.center.x,y:v.y-base.center.y}));ctx.save();ctx.translate(drag.x,drag.y);ctx.shadowColor='#d8f3ff';ctx.shadowBlur=18/cam.zoom;ctx.rotate(drag.angle);ctx.scale(drag.mirrored?-1:1,1);ctx.fillStyle='#d7ecffde';ctx.strokeStyle='#fff';ctx.lineWidth=3/cam.zoom;ctx.fill(path(local));ctx.stroke(path(local));ctx.restore()}ctx.restore();
 if(hint&&drag&&drag.mirrored!==hint.mirrored){message.textContent='ゴーストは正しい鏡像です — ダブルクリック／ダブルタップで反転'}else message.textContent=drag?'正しいHatへ近づけると吸着します':'Hatをドラッグして、宇宙をひらく';undoBtn.disabled=!undo.length;requestAnimationFrame(draw)}
function beginHat(q:Point){const w=world(q),base=engine.hats.get(engine.initialId())!;drag={x:w.x,y:w.y,angle:0,mirrored:base.mirrored};hintElapsed=0;hint=undefined;snap=undefined}
canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);void audio.start();isTouch=e.pointerType==='touch';pointer={x:e.offsetX,y:e.offsetY};pointerStart=pointer;last=pointer;if(e.button===1||e.button===2||e.shiftKey){panning=true;active=false;canvas.classList.add('dragging')}else{if(!drag)beginHat(pointer);else{const hit=partHit(world(pointer));if(hit==='move')mode='move';else if(hit==='rotate')mode='rotate';else{panning=true;active=false;canvas.classList.add('dragging');return}}active=true;hintTick=performance.now()}});
canvas.addEventListener('pointermove',e=>{pointer={x:e.offsetX,y:e.offsetY};if(panning){cam.x-=(pointer.x-last.x)/cam.zoom;cam.y-=(pointer.y-last.y)/cam.zoom;last=pointer;return}if(!drag)return;const w=world(pointer);if(!active){const hit=partHit(w);canvas.style.cursor=hit==='rotate'?'crosshair':hit==='move'?'grab':'default';return}if(mode==='move'){drag.x=w.x;drag.y=w.y}else drag.angle=Math.atan2(w.y-drag.y,w.x-drag.x);snap=nearestFrontier();const positionRadius=isTouch?1.65:1.25,angleRadius=isTouch ? .32 : .18;if(snap&&d2(snap.center,drag)<positionRadius**2&&Math.abs(normAngle(desiredAngle(snap)-drag.angle))<angleRadius&&snap.mirrored===drag.mirrored){drag.x=snap.center.x;drag.y=snap.center.y;drag.angle=desiredAngle(snap)}else snap=undefined});
let lastTouchTap=0;
canvas.addEventListener('pointerup',e=>{active=false;const wasPan=panning;if(panning){panning=false;canvas.classList.remove('dragging');persist()}if(!wasPan&&snap&&drag){opened.add(snap.id);undo.push(snap.id);if(undo.length>10)undo.shift();opening.set(snap.id,performance.now());audio.snap();drag=undefined;hint=undefined;snap=undefined;hintElapsed=0;if(opened.size>engine.hats.size*.6)engine.ensureLevel(engine.level+1);setTimeout(()=>spawnHat(true),5000);persist();lastTouchTap=0;return}if(e.pointerType==='touch'&&drag&&d2(pointer,pointerStart)<100){const now=performance.now();if(now-lastTouchTap<360){drag.mirrored=!drag.mirrored;lastTouchTap=0}else lastTouchTap=now}});
canvas.addEventListener('dblclick',e=>{e.preventDefault();if(drag)drag.mirrored=!drag.mirrored});
canvas.addEventListener('wheel',e=>{e.preventDefault();const before=world({x:e.offsetX,y:e.offsetY});cam.zoom=Math.max(12,Math.min(180,cam.zoom*Math.exp(-e.deltaY*.001)));const after=world({x:e.offsetX,y:e.offsetY});cam.x+=before.x-after.x;cam.y+=before.y-after.y;persist()},{passive:false});canvas.addEventListener('contextmenu',e=>e.preventDefault());
undoBtn.onclick=()=>{const id=undo.pop();if(id){opened.delete(id);persist()}};resetBtn.onclick=()=>{if(confirm('宇宙を最初のHat一枚へ戻しますか？'))reset()};soundBtn.onclick=async()=>{await audio.start();audio.set(!audio.muted);soundBtn.textContent=audio.muted?'音 ×':'音 ♪';persist()};
addEventListener('resize',resize);document.addEventListener('visibilitychange',()=>{if(document.hidden)persist()});
(async()=>{const s=await loadSave();if(s?.schemaVersion===1&&s.mathRuleSetVersion==='hat-htpf-v1'){const max=Math.max(3,...s.openedHatIds.map(id=>Number(id.match(/\/L(\d+)\//)?.[1]??0)));engine.ensureLevel(max);opened=new Set(s.openedHatIds.filter(id=>engine.hats.has(id)));undo=s.undo.filter(id=>opened.has(id)).slice(-10);cam=s.camera;audio.set(s.audio.muted,s.audio.volume);soundBtn.textContent=audio.muted?'音 ×':'音 ♪';if(!opened.size)reset()}else reset();resize();spawnHat()})();
